#!/bin/sh
#
# @name KLY Delta X3
#
# @type Quadrotor Wide
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
# @maintainer Hank Yang (hankyang94@gmail.com)
#

# sh /etc/init.d/rc.mc_defaults

## this is only used for testing with KLY delta X3
sh /etc/init.d/rc.kly_delta_x3_mc_defaults

set MIXER kly_delta_x3

set PWM_OUT 1234